CREATE TABLE IF NOT EXISTS feeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  state TEXT DEFAULT 'enabled'
);
CREATE TABLE IF NOT EXISTS feed_items (
  link TEXT NOT NULL PRIMARY KEY,
  title TEXT NOT NULL,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP,
  state TEXT DEFAULT 'unset',
  feed_id INTEGER NOT NULL,
  FOREIGN KEY (feed_id) REFERENCES feeds(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS migrations (
  id TEXT PRIMARY KEY NOT NULL,
  applied_on DATETIME DEFAULT CURRENT_TIMESTAMP
);